---
stages:
  - preview-stage
  - deploy-stage

# Template used to deploy Gitlab Pages based website as preview app or in production mode
.job_template:
  image:
    name: registry.gitlab.com/codrcodz/mkdocs-material-insiders-docker/image:mr-3
    entrypoint: ["/bin/sh", "-c"]
  variables:
    TZ: America/Chicago
    COPYRIGHT_HOLDER: "2023-2024 Matters of the Mind Therapy, PLLC"
  script:
    - /entrypoint.sh
    - mkdocs build --strict --verbose --site-dir public
  artifacts:
    paths:
      - public
   
pages:preview:
  stage: preview-stage
  extends:
    - .job_template
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always
  environment:
    name: "preview/${CI_PROJECT_NAME}/mr-${CI_MERGE_REQUEST_IID}"
    url: "https://${CI_PROJECT_NAMESPACE}.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/public/index.html"

pages:
  stage: deploy-stage
  extends:
    - .job_template
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
