---

site_name: Matters of the Mind

theme:
  name: material
  font:
    text: Comfortaa
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: custom
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.footer

markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition

use_directory_urls: true

extra_css:
  - stylesheets/extra.css

nav:
  - Welcome: "index.md"
  - Location: "location.md"
  - Services: "services.md"
  - Providers: "providers.md"
  - Rates: "rates.md"
  - Appointments: "appointments.md"
  - Contact: "contact.md"

plugins:
  - search

extra:
  social:
    - icon: fontawesome/solid/phone
      link: tel:1234567890
      name: Call us
    - icon: fontawesome/solid/paper-plane
      link: mailto:jasmine@motmtherapy.com
      name: Email us
    - icon: material/butterfly
      link: https://meetmonarch.com
      name: Check us out on Monarch
    - icon: simple/academia
      link: https://secure.helloalma.com/providers/jasmine-scott-cochran/
      name: Check us out on Alma
    - icon: fontawesome/solid/brain
      link: https://psychologytoday.com
      name: Check us out on Psychology Today
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/matters-of-the-mind-therapy-llc/
      name: Check us out on LinkedIn
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/motm-therapy/
      name: Check us out on Gitlab

copyright: Copyright &copy; 2023 Matters of the Mind Therapy, LLC

...

