---

site_name: Matters of the Mind

theme:
  name: material
  # Comment out the overrides line below to disable the announcement bar
  custom_dir: overrides
  font:
    text: Comfortaa
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: custom
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.footer

markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences

use_directory_urls: true

extra_css:
  - stylesheets/extra.css

nav:
  - Welcome: "index.md"
  - About:
    - Services: "services.md"
    - Location: "location.md"
    - 'Rates & Fees': "rates.md"
  - Providers:
    - "providers/index.md"
    - 'Jasmine Scott-Cochran': "providers/jasmine.md"
  - Appointments: "appointments.md"
  - Contact: "contact.md"

plugins:
  - search
  - privacy:
      links_attr_map:
        target: _blank

extra:
  social:
    - icon: fontawesome/solid/phone
      link: tel:2106222504
      name: Call us
    - icon: fontawesome/solid/paper-plane
      link: mailto:staff@motmtherapy.com
      name: Email us
    - icon: fontawesome/solid/calendar-days
      link: https://motmtherapy.com/portal
      name: Book an appointment or consultation on our client portal
    - icon: material/butterfly
      link: https://motmtherapy.com/monarch
      name: Check us out on Monarch
    - icon: simple/academia
      link: https://motmtherapy.com/alma
      name: Check us out on Alma
    - icon: fontawesome/solid/brain
      link: https://motmtherapy.com/psychology-today
      name: Check us out on Psychology Today
    - icon: fontawesome/brands/linkedin-in
      link: https://motmtherapy.com/linkedin
      name: Check us out on LinkedIn
    - icon: fontawesome/brands/gitlab
      link: https://motmtherapy.com/gitlab
      name: Check us out on Gitlab
    - icon: fontawesome/solid/up-long
      link: https://motmtherapy.com/status
      name: Check out our status page from UptimeRobot

copyright:   # This line is automatically populated at build time, do not modify it

...

