---

site_name: Matters of the Mind Therapy

theme:
  name: material
  font:
    text: Comfortaa
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition

use_directory_urls: true

extra_css:
  - stylesheets/extra.css

nav:
  - Welcome: "index.md"
  - About: "about.md"
  - Services: "services.md"
  - Rates: "rates.md"
  - Contact: "contact.md"

plugins:
  - search

...

