---

site_name: Matters of the Mind

theme:
  name: material
  font:
    text: Comfortaa
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: custom
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.footer

markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition

use_directory_urls: true

extra_css:
  - stylesheets/extra.css

nav:
  - Welcome: "index.md"
  - About:
    - Services: "services.md"
    - Location: "location.md"
    - 'Rates & Fees': "rates.md"
  - Providers:
    - "providers/index.md"
    - 'Jasmine Scott-Cochran': "providers/jasmine.md"
  - Appointments: "appointments.md"
  - Contact: "contact.md"

plugins:
  - search
  - privacy:
      links_attr_map:
        target: _blank

extra:
  social:
    - icon: fontawesome/solid/phone
      link: tel:2106222504
      name: Call us
    - icon: fontawesome/solid/paper-plane
      link: mailto:staff@motmtherapy.com
      name: Email us
    - icon: material/butterfly
      link: https://meetmonarch.com/therapist/jasmine-scott-cochran-ms-ncc-lpc-owner-therapist
      name: Check us out on Monarch
    - icon: simple/academia
      link: https://secure.helloalma.com/providers/jasmine-scott-cochran/
      name: Check us out on Alma
    - icon: fontawesome/solid/brain
      link: https://www.psychologytoday.com/us/therapists/jasmine-scott-cochran-san-antonio-tx/726906
      name: Check us out on Psychology Today
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/matters-of-the-mind-therapy-llc/
      name: Check us out on LinkedIn
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/motm-therapy/
      name: Check us out on Gitlab
    - icon: fontawesome/solid/up-long
      link: https://status.motmtherapy.com
      name: Check out our status page from UptimeRobot

copyright:   # This line is automatically populated at build time, do not modify it

...

