---

name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: squidfunk/mkdocs-material:9.1.4
    steps:
      - uses: actions/checkout@v3
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: apk add bash tzdata
      - run: cp /usr/share/zoneinfo/America/Chicago /etc/localtime
      - run: chmod +x ./timestamp.sh
      - run: ./timestamp.sh
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

...
